# Generated by Django 2.0.4 on 2018-04-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180413_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=models.ManyToManyField(to='users.Permission'),
        ),
    ]
