# Generated by Django 2.0.4 on 2018-04-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180413_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='idToken',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
