# Generated by Django 2.0.4 on 2018-04-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180414_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='Null', max_length=254),
        ),
    ]
