# Generated by Django 2.0.4 on 2018-04-13 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180413_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='resposible',
            new_name='responsible',
        ),
    ]
