# Generated by Django 2.0.4 on 2018-04-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20180418_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='state',
            new_name='status',
        ),
    ]
