# Generated by Django 2.0.4 on 2018-04-26 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180418_2204'),
        ('projects', '0007_auto_20180421_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('action', models.CharField(default=' ', max_length=1000)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
                ('targetActor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targetActor', to='users.User')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Task')),
                ('triggerActor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggerActor', to='users.User')),
            ],
        ),
    ]
