# Generated by Django 2.0.4 on 2018-05-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20180426_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentactivity',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='creationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
